# api/config/schema.yaml
# The list of types and properties we want to use
types:
    # Parent class of Person
    Thing:
        namespaces:
            class: "App\\Entity"
            interface: "Schema\\Model"
        properties:
            name: ~
    Person:
        namespaces:
            class: "App\\Entity"
            interface: "Schema\\Model"
        properties:
            familyName: ~
            givenName: ~
            additionalName: ~
            address: ~
    PostalAddress:
        namespaces:
            class: "App\\Entity"
            interface: "Schema\\Model"
        # Disable the generation of the class hierarchy for this type
        parent: false
        properties:
            # Force the type of the addressCountry property to text
            addressCountry: { range: "Text" }
            addressLocality: ~
            addressRegion: ~
            postOfficeBoxNumber: ~
            postalCode: ~
            streetAddress: ~