# RDFa/OWL files to import
rdfa:
    - http://vocab.linkeddata.es/vgo/GameOntologyv3.owl
    - 
        uri: https://raw.githubusercontent.com/MaastrichtU-IDS/semanticscience/master/ontology/sio/release/sio-subset-core.owl
        format: rdfxml
    
# Types to use from the imported ontologies
types:
    Session:
        vocabularyNamespace: http://purl.org/net/VideoGameOntology#
    Achievement:
        vocabularyNamespace: http://purl.org/net/VideoGameOntology#
    SIO_000001:
        vocabularyNamespace: http://semanticscience.org/resource/
        allProperties:        false
        


# OWL relation files to use
relations:
    # Default:
    - https://purl.org/goodrelations/v1.owl
    - https://raw.githubusercontent.com/MaastrichtU-IDS/semanticscience/master/ontology/sio/release/sio-subset-core.owl


# PHP namespaces
namespaces:
    # The namespace of the generated entities
    entity:               Entity # Example: App\Entity
    # The namespace of the generated enumerations
    enum:                 Enum # Example: App\Enum
    # The namespace of the generated interfaces
    interface:            Model # Example: App\Model


# IDs configuration
# id:
#     # Automatically add an id field to entities
#     generate:             true
#     # The ID generation strategy to use ("none" to not let the database generate IDs).
#     generationStrategy:   auto # One of "auto"; "none"; "uuid"; "mongoid"
#     # Is the ID writable? Only applicable if "generationStrategy" is "uuid".
#     writable:             false

# # Generate interfaces and use Doctrine's Resolve Target Entity feature
# useInterface:         false
# # Emit a warning if a property is not derived from GoodRelations
# checkIsGoodRelations: false
# # A license or any text to use as header of generated files
# header:               false # Example: // (c) Kévin Dunglas <dunglas@gmail.com>
# Debug mode
# debug:                false

# Doctrine
# doctrine:
#     # Use Doctrine's ArrayCollection instead of standard arrays
#     useCollection:        true
#     # The Resolve Target Entity Listener config file pass
#     resolveTargetEntityConfigPath: null

# Symfony Validator Component
# validator:
#     # Generate @Assert\Type annotation
#     assertType:           false

# The value of the phpDoc's @author annotation
# author:               false # Example: Kévin Dunglas <dunglas@gmail.com>
# # Visibility of entities fields
# fieldVisibility:      private # One of "private"; "protected"; "public"
# # Set this flag to false to not generate getter, setter, adder and remover methods
# accessorMethods:      true
# # Set this flag to true to generate fluent setter, adder and remover methods
# fluentMutatorMethods: false


# For types defined manually
# types:
    # # Prototype
    # id:
    #     # Namespace of the vocabulary the type belongs to.
    #     vocabularyNamespace:  'http://schema.org/'
    #     # Is the class abstract? (null to guess)
    #     abstract:             null
    #     # Is the class embeddable?
    #     embeddable:           false
    #     # Type namespaces
    #     namespaces:
    #         # The namespace for the generated class (override any other defined namespace)
    #         class:                null
    #         # The namespace for the generated interface (override any other defined namespace)
    #         interface:            null
    #     doctrine:
    #         # The Doctrine inheritance mapping type (override the guessed one)
    #         inheritanceMapping:   null
    #     # The parent class, set to false for a top level class
    #     parent:               false
    #     # If declaring a custom class, this will be the class from which properties type will be guessed
    #     guessFrom:            Thing
    #     # Import all existing properties
    #     allProperties:        false
    #     # Properties of this type to use
    #     properties:
    #         # Prototype
    #         id:
    #             # The property range
    #             range:                null # Example: Offer
    #             # The relation table name
    #             relationTableName:    null # Example: organization_member
    #             cardinality:          unknown # One of "(0..1)"; "(0..*)"; "(1..1)"; "(1..*)"; "(*..0)"; "(*..1)"; "(*..*)"; "unknown"
    #             # The doctrine column annotation content
    #             ormColumn:            null # Example: type="decimal", precision=5, scale=1, options={"comment" = "my comment"}
    #             # Symfony Serialization Groups
    #             groups:               []
    #             # Is the property readable?
    #             readable:             true
    #             # Is the property writable?
    #             writable:             true
    #             # Is the property nullable?
    #             nullable:             true
    #             # The property unique
    #             unique:               false
    #             # Is the property embedded?
    #             embedded:             false
    #             # The property columnPrefix
    #             columnPrefix:         false

# Annotation generators to use
# annotationGenerators:
#     # Defaults:
#     - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
#     - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
#     - ApiPlatform\SchemaGenerator\AnnotationGenerator\ApiPlatformCoreAnnotationGenerator
#     - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
#     - ApiPlatform\SchemaGenerator\AnnotationGenerator\SerializerGroupsAnnotationGenerator